Tt 003/003
sw21-tug/Team_02 pull request #50
Opened 2021-05-04 11:38 UTC by precap

2021-05-04 11:45 UTC, seichr commented
Bei den Commit-Messages bitte auf die Benennungsregeln achten. @steschi kann man aber trotzdem reinnehmen oder?

2021-05-05 05:51 UTC, seichr commented
Was mir auch noch auffällt ist das der Branch a Benennungsproblem hat. @steschi muss man das ändern?

2021-05-05 06:05 UTC, seichr requested changes

2021-05-05 06:05 UTC, seichr commented on TodoTasker/app/src/androidTest/java/com/backend/todo_tasker/DateTimePickRecordedTest.kt
> +                withId(R.id.item_date), withText(startsWith("1619971")),
Millisekunden nicht hardcoden bitte. => Test Failt

2021-05-05 06:05 UTC, seichr commented on TodoTasker/app/src/main/java/com/backend/todo_tasker/MainActivity.kt
> +        dateInputEditText.setOnClickListener {
Bitte in eigene Funktion auslagern. Die kannst dann im Layout angeben siehe EditText. Vl noch a klasse für die funktionsaufrufe.

2021-05-05 06:51 UTC, steschi commented
> Was mir auch noch auffällt ist das der Branch a Benennungsproblem hat. @steschi muss man das ändern?

Bin mir nicht sicher ob man "muss", aber die Konventionen einhalten is sicher net verkehrt

2021-05-05 07:18 UTC, seichr approved these changes

2021-05-05 07:22 UTC, merged